name: Dotnet Mvc 4.5 Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019
    steps:
    
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore IMS-Project.sln

    - name: Build Solution
      run: |
        msbuild.exe IMS-Project.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: Replace credentials
      run: |
        sed -i 's/__DB_USER__/${{ secrets.DB_USER }}/g' Web.config +
        sed -i 's/__DB-PASSWORD__/${{ secrets.DB_PASSWORD }}/g' Web.config +
        sed -i 's/__DB_SERVER__/${{ secrets.DB_SERVER }}/g' Web.config +
        sed -i 's/__DB_DATABASE/${{ secrets.DB_DATABASE }}/g' Web.config
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: EZRepBundle
        path: "./_build"        

    - name: Sync Files001
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: putracode2.somee.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./_build/
        server-dir: ./www.putracode2.somee.com/
        dangerous-clean-slate: true

    #- name: Login to Azure
     # uses: azure/login@v1
      #with:
       # creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    #- name: Publish Artifacts to Azure
     # uses: Azure/webapps-deploy@v2
      #with:
       # app-name: ezrep
        #package: "./_build"
        #slot-name: production        

